title: "それでもPerlと向き合わないといけない僕らのためのガイドブック"
summary: "Perlがいかにすごい言語なのかは理解している。\nけれども、僕らが書きたい言語じゃない。でも戦場に並んでいるあれこれはPerlで動いているし、それらが金を生み続けている。\nリプレースしたくとも単体テストもなければ仕様書もない。僕らに残された道はないのか。\nいや、一つある。僕らがPerlを理解し、愛し、本当の姿を取り戻させるのだ。\nこれは正しいPerlを追い求めるしかなかった一人の戦士が試行錯誤した記録である。"
topics: [perl]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - step1
  - step2
  - step3
