title: "AWS CloudWatchではじめるアプリケーション ログ/メトリクス 監視入門"
summary: "対象読者: ログ監視はなんとなくわかるけどメトリクス監視とは何かよくわからない人。\n適当にログをクラウドで貯めて監視しようとすると、ビジネスが成長する段階で困ることになるよ、と言われてもピンとこない人。"
topics: ['CloudWatch', 'aws', '監視']
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - step1
  - step2
  - step3
  - step4
  - step5
