title: "AWS CloudWatchで体験するアプリケーション ログ/メトリクス 監視入門"
summary: "対象読者: メトリクスって何それ美味しいの？という方。\nEC2やオンプレミスからECSに移行しようと思っているけどログどうしよう？という方。\nAPIのレスポンスタイムをアラームのトリガーにしたいな、と思っている方。\n\n基礎知識の要求: AWS ECS, Docker, Rails\n\n扱うもの:CloudWatch,FireLens,Athena,FluentBit,Kinesis,S3"
topics: ['CloudWatch', 'aws', '監視', 'fluentbit', 'athena']
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - step1
  - step2
  - step3
  - step4
  - step5
  - step6
  - step7
  - step8
  